inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - db/**/*
    - app/assets/**/*

Rails:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Lint/PercentStringArray:
  Exclude:
    - config/initializers/secure_headers.rb

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - app/indexes/*

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/AndOr:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/Lambda:
  EnforcedStyle: literal

Style/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line
