# PostgreSQL.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fanuniverse_development

test:
  <<: *default
  database: fanuniverse_test

production:
  <<: *default
  database: fanuniverse_production
  username: fanuniverse
  password: <%= ENV['FANUNIVERSE_DATABASE_PASSWORD'] %>
