default:
  image_root: /system/images
  asset_root: /assets

test:
  # Overrides default settings in test environment only.

development:
  # Overrides default settings in development environment only.

production:
  # Overrides default settings in production environment only.
