default:
  image_root: /
  asset_root: /

development:
  image_root: /uploads/images
  asset_root: /assets

production:
  image_root: //cookielessdomain.com/images
  asset_root: //cookielessdomain.com/assets
